/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/admin/blog/articles/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    get: operations["admin_blog_articles_list"];
    put?: never;
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    post: operations["admin_blog_articles_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/blog/articles/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    get: operations["admin_blog_articles_retrieve"];
    put?: never;
    post?: never;
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    delete: operations["admin_blog_articles_destroy"];
    options?: never;
    head?: never;
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    patch: operations["admin_blog_articles_partial_update"];
    trace?: never;
  };
  "/api/admin/blog/articles/{id}/preview-link/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    post: operations["admin_blog_articles_preview_link_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/blog/articles/{id}/translate/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description A draft copy in the other language, in the same translation group. */
    post: operations["admin_blog_articles_translate_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/blog/categories/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    get: operations["admin_blog_categories_list"];
    put?: never;
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    post: operations["admin_blog_categories_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/blog/categories/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    get: operations["admin_blog_categories_retrieve"];
    put?: never;
    post?: never;
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    delete: operations["admin_blog_categories_destroy"];
    options?: never;
    head?: never;
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    patch: operations["admin_blog_categories_partial_update"];
    trace?: never;
  };
  "/api/admin/blog/tags/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    get: operations["admin_blog_tags_list"];
    put?: never;
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    post: operations["admin_blog_tags_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/blog/tags/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    get: operations["admin_blog_tags_retrieve"];
    put?: never;
    post?: never;
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    delete: operations["admin_blog_tags_destroy"];
    options?: never;
    head?: never;
    /** @description DELETE answers 409 (not 500) when other rows still reference the object. */
    patch: operations["admin_blog_tags_partial_update"];
    trace?: never;
  };
  "/api/admin/cms/blocks/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["admin_cms_blocks_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/cms/blocks/{key}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["admin_cms_blocks_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["admin_cms_blocks_partial_update"];
    trace?: never;
  };
  "/api/admin/cms/items/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["admin_cms_items_list"];
    put?: never;
    post: operations["admin_cms_items_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/cms/items/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["admin_cms_items_retrieve"];
    put?: never;
    post?: never;
    delete: operations["admin_cms_items_destroy"];
    options?: never;
    head?: never;
    patch: operations["admin_cms_items_partial_update"];
    trace?: never;
  };
  "/api/admin/cms/items/reorder/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["admin_cms_items_reorder_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/cms/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["admin_cms_settings_retrieve"];
    put: operations["admin_cms_settings_update"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["admin_cms_settings_partial_update"];
    trace?: never;
  };
  "/api/admin/media/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["admin_media_list"];
    put?: never;
    post: operations["admin_media_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/media/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["admin_media_retrieve"];
    put?: never;
    post?: never;
    delete: operations["admin_media_destroy"];
    options?: never;
    head?: never;
    patch: operations["admin_media_partial_update"];
    trace?: never;
  };
  "/api/admin/media/{id}/original/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Redirects to a 60-second signed download via the gateway. */
    get: operations["admin_media_original_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/media/{id}/reprocess/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["admin_media_reprocess_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/portfolio/categories/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    get: operations["admin_portfolio_categories_list"];
    put?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    post: operations["admin_portfolio_categories_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/portfolio/categories/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    get: operations["admin_portfolio_categories_retrieve"];
    put?: never;
    post?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    delete: operations["admin_portfolio_categories_destroy"];
    options?: never;
    head?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    patch: operations["admin_portfolio_categories_partial_update"];
    trace?: never;
  };
  "/api/admin/portfolio/categories/reorder/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    post: operations["admin_portfolio_categories_reorder_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/portfolio/projects/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    get: operations["admin_portfolio_projects_list"];
    put?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    post: operations["admin_portfolio_projects_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/portfolio/projects/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    get: operations["admin_portfolio_projects_retrieve"];
    put?: never;
    post?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    delete: operations["admin_portfolio_projects_destroy"];
    options?: never;
    head?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    patch: operations["admin_portfolio_projects_partial_update"];
    trace?: never;
  };
  "/api/admin/portfolio/projects/reorder/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    post: operations["admin_portfolio_projects_reorder_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/pricing/groups/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    get: operations["admin_pricing_groups_list"];
    put?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    post: operations["admin_pricing_groups_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/pricing/groups/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    get: operations["admin_pricing_groups_retrieve"];
    put?: never;
    post?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    delete: operations["admin_pricing_groups_destroy"];
    options?: never;
    head?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    patch: operations["admin_pricing_groups_partial_update"];
    trace?: never;
  };
  "/api/admin/pricing/groups/reorder/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    post: operations["admin_pricing_groups_reorder_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/pricing/packages/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    get: operations["admin_pricing_packages_list"];
    put?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    post: operations["admin_pricing_packages_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/pricing/packages/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    get: operations["admin_pricing_packages_retrieve"];
    put?: never;
    post?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    delete: operations["admin_pricing_packages_destroy"];
    options?: never;
    head?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    patch: operations["admin_pricing_packages_partial_update"];
    trace?: never;
  };
  "/api/admin/pricing/packages/reorder/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description New rows go to the end of the list; create and update are written to the audit log. */
    post: operations["admin_pricing_packages_reorder_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/settings/watermark": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["admin_settings_watermark_retrieve"];
    put: operations["admin_settings_watermark_update"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/csrf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Set the CSRF cookie */
    get: operations["auth_csrf_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_login_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_logout_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["auth_me_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_password_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/recovery-codes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_recovery_codes_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/totp/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_totp_confirm_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/totp/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["auth_totp_setup_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_verify_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/blog/articles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["public_blog_articles_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/blog/articles/{lang}/{slug}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["public_blog_article_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/blog/preview/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["public_blog_preview_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/blog/taxonomy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["public_blog_taxonomy_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/packages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Published groups with their published packages; groups without packages are left out. */
    get: operations["public_packages_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/portfolio": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["public_portfolio_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/portfolio/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["public_project_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/site": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Everything the public pages need in one cacheable response. Only published items are included. */
    get: operations["public_site_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/sitemap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Raw material for sitemap.xml: only what visitors can actually open (never drafts or scheduled). */
    get: operations["public_sitemap_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Alternate: {
      language: string;
      slug: string;
    };
    Article: {
      readonly id: number;
      language: components["schemas"]["LanguageEnum"];
      /** Format: uuid */
      readonly translation_group: string;
      slug?: string;
      title: string;
      summary?: string;
      body?: unknown;
      readonly body_media: {
        [key: string]: components["schemas"]["PublicMedia"];
      };
      /** Format: uuid */
      cover?: string | null;
      readonly cover_detail: components["schemas"]["PublicMedia"] | null;
      category?: number | null;
      tags?: number[];
      status?: components["schemas"]["ArticleStatusEnum"];
      /** Format: date-time */
      published_at?: string | null;
      seo_title?: string;
      seo_description?: string;
      /** Format: uuid */
      og_image?: string | null;
      readonly og_image_detail: components["schemas"]["PublicMedia"] | null;
      related_projects?: number[];
      readonly reading_minutes: number;
      readonly is_live: boolean;
      readonly translations: components["schemas"]["Translation"][];
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly updated_at: string;
    };
    /** @description One row of the panel's list: no body, no embedded-media lookups, no translation queries. */
    ArticleList: {
      readonly id: number;
      readonly language: components["schemas"]["LanguageEnum"];
      /** Format: uuid */
      readonly translation_group: string;
      slug?: string;
      readonly title: string;
      readonly summary: string;
      readonly category: number | null;
      readonly status: components["schemas"]["ArticleStatusEnum"];
      /** Format: date-time */
      readonly published_at: string | null;
      readonly reading_minutes: number;
      readonly is_live: boolean;
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly updated_at: string;
    };
    ArticleMoved: {
      slug: string;
    };
    /**
     * @description * `draft` - پیش‌نویس
     *     * `published` - منتشرشده
     * @enum {string}
     */
    ArticleStatusEnum: "draft" | "published";
    AuthUser: {
      username: string;
      display_name: string;
    };
    /** @enum {unknown} */
    BlankEnum: "";
    BlogCategory: {
      readonly id: number;
      slug?: string;
      title_fa: string;
      title_en?: string;
      description_fa?: string;
      description_en?: string;
      readonly article_count: number;
    };
    BlogTag: {
      readonly id: number;
      slug?: string;
      title_fa: string;
      title_en?: string;
      readonly article_count: number;
    };
    BlogTaxonomyItem: {
      slug: string;
      title_fa: string;
      title_en: string;
      count: number;
    };
    /** @description `slug` may be left empty: it is then made from the English (or Persian) title. */
    Category: {
      readonly id: number;
      slug?: string;
      title_fa: string;
      title_en?: string;
      description_fa?: string;
      description_en?: string;
      /** Format: uuid */
      cover?: string | null;
      readonly cover_detail: components["schemas"]["PublicMedia"] | null;
      readonly position: number;
      is_published?: boolean;
      readonly project_count: number;
    };
    Code: {
      code: string;
    };
    /**
     * @description * `hero_slide` - اسلاید هیرو
     *     * `service` - خدمت
     *     * `process_step` - مرحله‌ی همکاری
     *     * `client` - مشتری
     *     * `testimonial` - نظر مشتری
     *     * `behind_scenes` - پشت صحنه
     *     * `faq` - پرسش پرتکرار
     *     * `nav_link` - پیوند منو
     * @enum {string}
     */
    CollectionEnum:
      | "hero_slide"
      | "service"
      | "process_step"
      | "client"
      | "testimonial"
      | "behind_scenes"
      | "faq"
      | "nav_link";
    ContentBlock: {
      readonly key: string;
      readonly display_name: string;
      readonly group: string;
      readonly kind: string;
      text_fa?: string;
      text_en?: string;
      /** Format: uuid */
      media?: string | null;
      readonly media_detail: components["schemas"]["PublicMedia"] | null;
      /** Format: date-time */
      readonly updated_at: string;
    };
    ContentItem: {
      readonly id: number;
      collection: components["schemas"]["CollectionEnum"];
      readonly position: number;
      is_published?: boolean;
      title_fa?: string;
      title_en?: string;
      subtitle_fa?: string;
      subtitle_en?: string;
      body_fa?: string;
      body_en?: string;
      link_url?: string;
      /** Format: uuid */
      media?: string | null;
      readonly media_detail: components["schemas"]["PublicMedia"] | null;
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly updated_at: string;
    };
    Credentials: {
      username: string;
      password: string;
    };
    Error: {
      code: string;
      detail: string;
    };
    Feature: {
      text_fa: string;
      text_en?: string;
      /** @description False shows the line as not included */
      included?: boolean;
    };
    /**
     * @description * `image` - تصویر
     *     * `video` - ویدیو
     * @enum {string}
     */
    KindEnum: "image" | "video";
    /**
     * @description * `fa` - فارسی
     *     * `en` - English
     * @enum {string}
     */
    LanguageEnum: "fa" | "en";
    MediaAsset: {
      /** Format: uuid */
      readonly id: string;
      readonly kind: components["schemas"]["KindEnum"];
      readonly status: components["schemas"]["StatusEnum"];
      readonly original_filename: string;
      readonly mime: string;
      readonly size_bytes: number;
      readonly width: number | null;
      readonly height: number | null;
      /** Format: double */
      readonly duration_seconds: number | null;
      title?: string;
      /** متن جایگزین (فارسی) */
      alt_fa?: string;
      /** متن جایگزین (انگلیسی) */
      alt_en?: string;
      readonly lqip: string;
      readonly watermarked: boolean;
      readonly error: string;
      readonly usage_count: number;
      readonly variants: components["schemas"]["MediaVariant"][];
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly updated_at: string;
    };
    MediaUpload: {
      /** Format: uri */
      file: string;
    };
    MediaVariant: {
      name: string;
      format: string;
      readonly url: string;
      width: number;
      height: number;
      /** Format: int64 */
      size_bytes: number;
    };
    Package: {
      readonly id: number;
      group: number;
      title_fa: string;
      title_en?: string;
      summary_fa?: string;
      summary_en?: string;
      price_mode?: components["schemas"]["PriceModeEnum"];
      /**
       * Format: int64
       * @description Toman
       */
      price_amount?: number | null;
      /** @description e.g. «به ازای هر محصول» */
      price_unit_fa?: string;
      price_unit_en?: string;
      /** @description e.g. «محبوب» */
      badge_fa?: string;
      badge_en?: string;
      is_featured?: boolean;
      is_published?: boolean;
      readonly position: number;
      features?: components["schemas"]["Feature"][];
    };
    PackageGroup: {
      readonly id: number;
      title_fa: string;
      title_en?: string;
      description_fa?: string;
      description_en?: string;
      readonly position: number;
      is_published?: boolean;
      readonly package_count: number;
    };
    PaginatedMediaAssetList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["MediaAsset"][];
    };
    Password: {
      password: string;
    };
    PasswordChange: {
      current_password: string;
      new_password: string;
    };
    PatchedArticle: {
      readonly id?: number;
      language?: components["schemas"]["LanguageEnum"];
      /** Format: uuid */
      readonly translation_group?: string;
      slug?: string;
      title?: string;
      summary?: string;
      body?: unknown;
      readonly body_media?: {
        [key: string]: components["schemas"]["PublicMedia"];
      };
      /** Format: uuid */
      cover?: string | null;
      readonly cover_detail?: components["schemas"]["PublicMedia"] | null;
      category?: number | null;
      tags?: number[];
      status?: components["schemas"]["ArticleStatusEnum"];
      /** Format: date-time */
      published_at?: string | null;
      seo_title?: string;
      seo_description?: string;
      /** Format: uuid */
      og_image?: string | null;
      readonly og_image_detail?: components["schemas"]["PublicMedia"] | null;
      related_projects?: number[];
      readonly reading_minutes?: number;
      readonly is_live?: boolean;
      readonly translations?: components["schemas"]["Translation"][];
      /** Format: date-time */
      readonly created_at?: string;
      /** Format: date-time */
      readonly updated_at?: string;
    };
    PatchedBlogCategory: {
      readonly id?: number;
      slug?: string;
      title_fa?: string;
      title_en?: string;
      description_fa?: string;
      description_en?: string;
      readonly article_count?: number;
    };
    PatchedBlogTag: {
      readonly id?: number;
      slug?: string;
      title_fa?: string;
      title_en?: string;
      readonly article_count?: number;
    };
    /** @description `slug` may be left empty: it is then made from the English (or Persian) title. */
    PatchedCategory: {
      readonly id?: number;
      slug?: string;
      title_fa?: string;
      title_en?: string;
      description_fa?: string;
      description_en?: string;
      /** Format: uuid */
      cover?: string | null;
      readonly cover_detail?: components["schemas"]["PublicMedia"] | null;
      readonly position?: number;
      is_published?: boolean;
      readonly project_count?: number;
    };
    PatchedContentBlock: {
      readonly key?: string;
      readonly display_name?: string;
      readonly group?: string;
      readonly kind?: string;
      text_fa?: string;
      text_en?: string;
      /** Format: uuid */
      media?: string | null;
      readonly media_detail?: components["schemas"]["PublicMedia"] | null;
      /** Format: date-time */
      readonly updated_at?: string;
    };
    PatchedContentItem: {
      readonly id?: number;
      collection?: components["schemas"]["CollectionEnum"];
      readonly position?: number;
      is_published?: boolean;
      title_fa?: string;
      title_en?: string;
      subtitle_fa?: string;
      subtitle_en?: string;
      body_fa?: string;
      body_en?: string;
      link_url?: string;
      /** Format: uuid */
      media?: string | null;
      readonly media_detail?: components["schemas"]["PublicMedia"] | null;
      /** Format: date-time */
      readonly created_at?: string;
      /** Format: date-time */
      readonly updated_at?: string;
    };
    PatchedMediaAsset: {
      /** Format: uuid */
      readonly id?: string;
      readonly kind?: components["schemas"]["KindEnum"];
      readonly status?: components["schemas"]["StatusEnum"];
      readonly original_filename?: string;
      readonly mime?: string;
      readonly size_bytes?: number;
      readonly width?: number | null;
      readonly height?: number | null;
      /** Format: double */
      readonly duration_seconds?: number | null;
      title?: string;
      /** متن جایگزین (فارسی) */
      alt_fa?: string;
      /** متن جایگزین (انگلیسی) */
      alt_en?: string;
      readonly lqip?: string;
      readonly watermarked?: boolean;
      readonly error?: string;
      readonly usage_count?: number;
      readonly variants?: components["schemas"]["MediaVariant"][];
      /** Format: date-time */
      readonly created_at?: string;
      /** Format: date-time */
      readonly updated_at?: string;
    };
    PatchedPackage: {
      readonly id?: number;
      group?: number;
      title_fa?: string;
      title_en?: string;
      summary_fa?: string;
      summary_en?: string;
      price_mode?: components["schemas"]["PriceModeEnum"];
      /**
       * Format: int64
       * @description Toman
       */
      price_amount?: number | null;
      /** @description e.g. «به ازای هر محصول» */
      price_unit_fa?: string;
      price_unit_en?: string;
      /** @description e.g. «محبوب» */
      badge_fa?: string;
      badge_en?: string;
      is_featured?: boolean;
      is_published?: boolean;
      readonly position?: number;
      features?: components["schemas"]["Feature"][];
    };
    PatchedPackageGroup: {
      readonly id?: number;
      title_fa?: string;
      title_en?: string;
      description_fa?: string;
      description_en?: string;
      readonly position?: number;
      is_published?: boolean;
      readonly package_count?: number;
    };
    /** @description `slug` may be left empty: it is then made from the English (or Persian) title. */
    PatchedProject: {
      readonly id?: number;
      slug?: string;
      category?: number | null;
      style?: components["schemas"]["StyleEnum"] | components["schemas"]["BlankEnum"];
      title_fa?: string;
      title_en?: string;
      summary_fa?: string;
      summary_en?: string;
      /** @description Case study */
      body_fa?: string;
      body_en?: string;
      client_fa?: string;
      client_en?: string;
      year?: number | null;
      /** Format: uuid */
      cover?: string | null;
      readonly cover_detail?: components["schemas"]["PublicMedia"] | null;
      is_featured?: boolean;
      is_published?: boolean;
      readonly position?: number;
      images?: components["schemas"]["ProjectImage"][];
      /** Format: date-time */
      readonly created_at?: string;
      /** Format: date-time */
      readonly updated_at?: string;
    };
    PatchedSiteSettings: {
      /** Format: uuid */
      logo?: string | null;
      /** Format: uuid */
      og_image?: string | null;
      readonly logo_detail?: components["schemas"]["PublicMedia"] | null;
      readonly og_image_detail?: components["schemas"]["PublicMedia"] | null;
      brand_name_fa?: string;
      brand_name_en?: string;
      tagline_fa?: string;
      tagline_en?: string;
      /** @description Default meta description */
      description_fa?: string;
      description_en?: string;
      phone?: string;
      email?: string;
      whatsapp?: string;
      telegram?: string;
      instagram?: string;
      address_fa?: string;
      address_en?: string;
      map_url?: string;
      footer_text_fa?: string;
      footer_text_en?: string;
      /** Format: date-time */
      readonly updated_at?: string;
    };
    /**
     * @description * `bottom_right` - پایین راست
     *     * `bottom_left` - پایین چپ
     *     * `top_right` - بالا راست
     *     * `top_left` - بالا چپ
     *     * `center` - وسط
     * @enum {string}
     */
    PositionEnum: "bottom_right" | "bottom_left" | "top_right" | "top_left" | "center";
    PreviewLink: {
      token: string;
      expires_in: number;
    };
    /**
     * @description * `from` - از … شروع می‌شود
     *     * `fixed` - قیمت ثابت
     *     * `inquiry` - استعلام
     * @enum {string}
     */
    PriceModeEnum: "from" | "fixed" | "inquiry";
    /** @description `slug` may be left empty: it is then made from the English (or Persian) title. */
    Project: {
      readonly id: number;
      slug?: string;
      category?: number | null;
      style?: components["schemas"]["StyleEnum"] | components["schemas"]["BlankEnum"];
      title_fa: string;
      title_en?: string;
      summary_fa?: string;
      summary_en?: string;
      /** @description Case study */
      body_fa?: string;
      body_en?: string;
      client_fa?: string;
      client_en?: string;
      year?: number | null;
      /** Format: uuid */
      cover?: string | null;
      readonly cover_detail: components["schemas"]["PublicMedia"] | null;
      is_featured?: boolean;
      is_published?: boolean;
      readonly position: number;
      images?: components["schemas"]["ProjectImage"][];
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly updated_at: string;
    };
    ProjectImage: {
      /** Format: uuid */
      media: string;
      readonly media_detail: components["schemas"]["PublicMedia"];
      caption_fa?: string;
      caption_en?: string;
    };
    PublicBlock: {
      readonly fa: string;
      readonly en: string;
      readonly media: components["schemas"]["PublicMedia"] | null;
    };
    PublicBlogArticle: {
      readonly language: components["schemas"]["LanguageEnum"];
      readonly slug: string;
      readonly title: string;
      readonly summary: string;
      readonly cover: components["schemas"]["PublicMedia"] | null;
      readonly category: components["schemas"]["PublicBlogCategory"] | null;
      readonly tags: components["schemas"]["PublicBlogTag"][];
      readonly reading_minutes: number;
      /** Format: date-time */
      readonly published_at: string | null;
    };
    PublicBlogArticleDetail: {
      readonly language: components["schemas"]["LanguageEnum"];
      readonly slug: string;
      readonly title: string;
      readonly summary: string;
      readonly cover: components["schemas"]["PublicMedia"] | null;
      readonly category: components["schemas"]["PublicBlogCategory"] | null;
      readonly tags: components["schemas"]["PublicBlogTag"][];
      readonly reading_minutes: number;
      /** Format: date-time */
      readonly published_at: string | null;
      readonly body_html: string;
      readonly seo_title: string;
      readonly seo_description: string;
      readonly og_image: components["schemas"]["PublicMedia"] | null;
      readonly alternates: components["schemas"]["Alternate"][];
      readonly related_articles: components["schemas"]["PublicBlogArticle"][];
      readonly related_projects: components["schemas"]["PublicProject"][];
      readonly previous: string | null;
      readonly next: string | null;
    };
    PublicBlogArticlePage: {
      count: number;
      page: number;
      pages: number;
      results: components["schemas"]["PublicBlogArticle"][];
    };
    PublicBlogCategory: {
      readonly slug: string;
      readonly title_fa: string;
      readonly title_en: string;
    };
    PublicBlogTag: {
      readonly slug: string;
      readonly title_fa: string;
      readonly title_en: string;
    };
    PublicBlogTaxonomy: {
      categories: components["schemas"]["BlogTaxonomyItem"][];
      tags: components["schemas"]["BlogTaxonomyItem"][];
    };
    PublicCategory: {
      readonly slug: string;
      readonly title_fa: string;
      readonly title_en: string;
      readonly description_fa: string;
      readonly description_en: string;
      readonly cover: components["schemas"]["PublicMedia"] | null;
      readonly project_count: number;
    };
    PublicCollections: {
      hero_slide: components["schemas"]["PublicItem"][];
      service: components["schemas"]["PublicItem"][];
      process_step: components["schemas"]["PublicItem"][];
      client: components["schemas"]["PublicItem"][];
      testimonial: components["schemas"]["PublicItem"][];
      behind_scenes: components["schemas"]["PublicItem"][];
      faq: components["schemas"]["PublicItem"][];
      nav_link: components["schemas"]["PublicItem"][];
    };
    PublicFeature: {
      readonly text_fa: string;
      readonly text_en: string;
      /** @description False shows the line as not included */
      readonly included: boolean;
    };
    PublicGroup: {
      readonly id: number;
      readonly title_fa: string;
      readonly title_en: string;
      readonly description_fa: string;
      readonly description_en: string;
      readonly packages: components["schemas"]["PublicPackage"][];
    };
    PublicImage: {
      readonly media: components["schemas"]["PublicMedia"];
      readonly caption_fa: string;
      readonly caption_en: string;
    };
    PublicItem: {
      readonly id: number;
      readonly title_fa: string;
      readonly title_en: string;
      readonly subtitle_fa: string;
      readonly subtitle_en: string;
      readonly body_fa: string;
      readonly body_en: string;
      readonly link_url: string;
      readonly media: components["schemas"]["PublicMedia"] | null;
    };
    /** @description What a visitor may know about a file: sizes, alt texts and the public variant URLs. */
    PublicMedia: {
      /** Format: uuid */
      readonly id: string;
      readonly kind: components["schemas"]["KindEnum"];
      readonly width: number | null;
      readonly height: number | null;
      /** Format: double */
      readonly duration_seconds: number | null;
      /** متن جایگزین (فارسی) */
      readonly alt_fa: string;
      /** متن جایگزین (انگلیسی) */
      readonly alt_en: string;
      readonly lqip: string;
      readonly variants: components["schemas"]["MediaVariant"][];
    };
    PublicPackage: {
      readonly id: number;
      readonly title_fa: string;
      readonly title_en: string;
      readonly summary_fa: string;
      readonly summary_en: string;
      readonly price_mode: components["schemas"]["PriceModeEnum"];
      /** @description Toman */
      readonly price_amount: number | null;
      /** @description e.g. «به ازای هر محصول» */
      readonly price_unit_fa: string;
      readonly price_unit_en: string;
      /** @description e.g. «محبوب» */
      readonly badge_fa: string;
      readonly badge_en: string;
      readonly is_featured: boolean;
      readonly features: components["schemas"]["PublicFeature"][];
    };
    PublicPackages: {
      groups: components["schemas"]["PublicGroup"][];
    };
    PublicPortfolio: {
      categories: components["schemas"]["PublicCategory"][];
      projects: components["schemas"]["PublicProject"][];
    };
    PublicProject: {
      readonly slug: string;
      readonly category: string;
      readonly style: components["schemas"]["StyleEnum"];
      readonly title_fa: string;
      readonly title_en: string;
      readonly summary_fa: string;
      readonly summary_en: string;
      readonly client_fa: string;
      readonly client_en: string;
      readonly year: number | null;
      readonly is_featured: boolean;
      readonly cover: components["schemas"]["PublicMedia"] | null;
    };
    PublicProjectDetail: {
      readonly slug: string;
      readonly category: string;
      readonly style: components["schemas"]["StyleEnum"];
      readonly title_fa: string;
      readonly title_en: string;
      readonly summary_fa: string;
      readonly summary_en: string;
      readonly client_fa: string;
      readonly client_en: string;
      readonly year: number | null;
      readonly is_featured: boolean;
      readonly cover: components["schemas"]["PublicMedia"] | null;
      /** @description Case study */
      readonly body_fa: string;
      readonly body_en: string;
      readonly images: components["schemas"]["PublicImage"][];
      readonly previous: string | null;
      readonly next: string | null;
    };
    PublicSettings: {
      readonly logo: components["schemas"]["PublicMedia"] | null;
      readonly og_image: components["schemas"]["PublicMedia"] | null;
      readonly brand_name_fa: string;
      readonly brand_name_en: string;
      readonly tagline_fa: string;
      readonly tagline_en: string;
      /** @description Default meta description */
      readonly description_fa: string;
      readonly description_en: string;
      readonly phone: string;
      /** Format: email */
      readonly email: string;
      readonly whatsapp: string;
      readonly telegram: string;
      readonly instagram: string;
      readonly address_fa: string;
      readonly address_en: string;
      /** Format: uri */
      readonly map_url: string;
      readonly footer_text_fa: string;
      readonly footer_text_en: string;
    };
    PublicSite: {
      settings: components["schemas"]["PublicSettings"];
      blocks: {
        [key: string]: components["schemas"]["PublicBlock"];
      };
      collections: components["schemas"]["PublicCollections"];
    };
    PublicSitemap: {
      projects: components["schemas"]["SitemapProject"][];
      articles: components["schemas"]["SitemapArticle"][];
    };
    RecoveryCodes: {
      recovery_codes: string[];
    };
    Reorder: {
      collection: components["schemas"]["CollectionEnum"];
      ids: number[];
    };
    ReorderIds: {
      ids: number[];
    };
    SiteSettings: {
      /** Format: uuid */
      logo?: string | null;
      /** Format: uuid */
      og_image?: string | null;
      readonly logo_detail: components["schemas"]["PublicMedia"] | null;
      readonly og_image_detail: components["schemas"]["PublicMedia"] | null;
      brand_name_fa?: string;
      brand_name_en?: string;
      tagline_fa?: string;
      tagline_en?: string;
      /** @description Default meta description */
      description_fa?: string;
      description_en?: string;
      phone?: string;
      email?: string;
      whatsapp?: string;
      telegram?: string;
      instagram?: string;
      address_fa?: string;
      address_en?: string;
      map_url?: string;
      footer_text_fa?: string;
      footer_text_en?: string;
      /** Format: date-time */
      readonly updated_at: string;
    };
    SitemapAlternate: {
      language: string;
      slug: string;
    };
    SitemapArticle: {
      language: string;
      slug: string;
      /** Format: date-time */
      updated_at: string;
      alternates: components["schemas"]["SitemapAlternate"][];
    };
    SitemapProject: {
      slug: string;
      /** Format: date-time */
      updated_at: string;
    };
    State: {
      state: components["schemas"]["StateEnum"];
      user: components["schemas"]["AuthUser"] | null;
    };
    /**
     * @description * `anonymous` - anonymous
     *     * `otp_required` - otp_required
     *     * `enrollment_required` - enrollment_required
     *     * `verified` - verified
     * @enum {string}
     */
    StateEnum: "anonymous" | "otp_required" | "enrollment_required" | "verified";
    /**
     * @description * `pending` - در صف
     *     * `processing` - در حال پردازش
     *     * `ready` - آماده
     *     * `failed` - ناموفق
     * @enum {string}
     */
    StatusEnum: "pending" | "processing" | "ready" | "failed";
    /**
     * @description * `low_key` - Low-key
     *     * `high_key` - High-key
     *     * `natural` - نور طبیعی
     * @enum {string}
     */
    StyleEnum: "low_key" | "high_key" | "natural";
    TotpSetup: {
      otpauth_uri: string;
      secret: string;
      qr_data_uri: string;
    };
    Translation: {
      id: number;
      language: string;
      slug: string;
      status: string;
    };
    WatermarkSetting: {
      enabled?: boolean;
      text?: string;
      /** Format: double */
      opacity?: number;
      position?: components["schemas"]["PositionEnum"];
      /**
       * Format: double
       * @description text height / width
       */
      size_ratio?: number;
      /** Format: date-time */
      readonly updated_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  admin_blog_articles_list: {
    parameters: {
      query?: {
        category?: number;
        language?: "en" | "fa";
        q?: string;
        status?: "draft" | "published";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArticleList"][];
        };
      };
    };
  };
  admin_blog_articles_create: {
    parameters: {
      query?: {
        category?: number;
        language?: "en" | "fa";
        q?: string;
        status?: "draft" | "published";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Article"];
        "application/x-www-form-urlencoded": components["schemas"]["Article"];
        "multipart/form-data": components["schemas"]["Article"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Article"];
        };
      };
    };
  };
  admin_blog_articles_retrieve: {
    parameters: {
      query?: {
        category?: number;
        language?: "en" | "fa";
        q?: string;
        status?: "draft" | "published";
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این article را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Article"];
        };
      };
    };
  };
  admin_blog_articles_destroy: {
    parameters: {
      query?: {
        category?: number;
        language?: "en" | "fa";
        q?: string;
        status?: "draft" | "published";
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این article را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_blog_articles_partial_update: {
    parameters: {
      query?: {
        category?: number;
        language?: "en" | "fa";
        q?: string;
        status?: "draft" | "published";
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این article را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedArticle"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedArticle"];
        "multipart/form-data": components["schemas"]["PatchedArticle"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Article"];
        };
      };
    };
  };
  admin_blog_articles_preview_link_create: {
    parameters: {
      query?: {
        category?: number;
        language?: "en" | "fa";
        q?: string;
        status?: "draft" | "published";
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این article را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreviewLink"];
        };
      };
    };
  };
  admin_blog_articles_translate_create: {
    parameters: {
      query?: {
        category?: number;
        language?: "en" | "fa";
        q?: string;
        status?: "draft" | "published";
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این article را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Article"];
        };
      };
    };
  };
  admin_blog_categories_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogCategory"][];
        };
      };
    };
  };
  admin_blog_categories_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BlogCategory"];
        "application/x-www-form-urlencoded": components["schemas"]["BlogCategory"];
        "multipart/form-data": components["schemas"]["BlogCategory"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogCategory"];
        };
      };
    };
  };
  admin_blog_categories_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این category را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogCategory"];
        };
      };
    };
  };
  admin_blog_categories_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این category را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_blog_categories_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این category را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedBlogCategory"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedBlogCategory"];
        "multipart/form-data": components["schemas"]["PatchedBlogCategory"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogCategory"];
        };
      };
    };
  };
  admin_blog_tags_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogTag"][];
        };
      };
    };
  };
  admin_blog_tags_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BlogTag"];
        "application/x-www-form-urlencoded": components["schemas"]["BlogTag"];
        "multipart/form-data": components["schemas"]["BlogTag"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogTag"];
        };
      };
    };
  };
  admin_blog_tags_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این tag را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogTag"];
        };
      };
    };
  };
  admin_blog_tags_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این tag را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_blog_tags_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این tag را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedBlogTag"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedBlogTag"];
        "multipart/form-data": components["schemas"]["PatchedBlogTag"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogTag"];
        };
      };
    };
  };
  admin_cms_blocks_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentBlock"][];
        };
      };
    };
  };
  admin_cms_blocks_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentBlock"];
        };
      };
    };
  };
  admin_cms_blocks_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedContentBlock"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedContentBlock"];
        "multipart/form-data": components["schemas"]["PatchedContentBlock"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentBlock"];
        };
      };
    };
  };
  admin_cms_items_list: {
    parameters: {
      query?: {
        collection?:
          | "behind_scenes"
          | "client"
          | "faq"
          | "hero_slide"
          | "nav_link"
          | "process_step"
          | "service"
          | "testimonial";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItem"][];
        };
      };
    };
  };
  admin_cms_items_create: {
    parameters: {
      query?: {
        collection?:
          | "behind_scenes"
          | "client"
          | "faq"
          | "hero_slide"
          | "nav_link"
          | "process_step"
          | "service"
          | "testimonial";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContentItem"];
        "application/x-www-form-urlencoded": components["schemas"]["ContentItem"];
        "multipart/form-data": components["schemas"]["ContentItem"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItem"];
        };
      };
    };
  };
  admin_cms_items_retrieve: {
    parameters: {
      query?: {
        collection?:
          | "behind_scenes"
          | "client"
          | "faq"
          | "hero_slide"
          | "nav_link"
          | "process_step"
          | "service"
          | "testimonial";
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این content item را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItem"];
        };
      };
    };
  };
  admin_cms_items_destroy: {
    parameters: {
      query?: {
        collection?:
          | "behind_scenes"
          | "client"
          | "faq"
          | "hero_slide"
          | "nav_link"
          | "process_step"
          | "service"
          | "testimonial";
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این content item را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_cms_items_partial_update: {
    parameters: {
      query?: {
        collection?:
          | "behind_scenes"
          | "client"
          | "faq"
          | "hero_slide"
          | "nav_link"
          | "process_step"
          | "service"
          | "testimonial";
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این content item را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedContentItem"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedContentItem"];
        "multipart/form-data": components["schemas"]["PatchedContentItem"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItem"];
        };
      };
    };
  };
  admin_cms_items_reorder_create: {
    parameters: {
      query?: {
        collection?:
          | "behind_scenes"
          | "client"
          | "faq"
          | "hero_slide"
          | "nav_link"
          | "process_step"
          | "service"
          | "testimonial";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Reorder"];
        "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
        "multipart/form-data": components["schemas"]["Reorder"];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_cms_settings_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteSettings"];
        };
      };
    };
  };
  admin_cms_settings_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["SiteSettings"];
        "application/x-www-form-urlencoded": components["schemas"]["SiteSettings"];
        "multipart/form-data": components["schemas"]["SiteSettings"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteSettings"];
        };
      };
    };
  };
  admin_cms_settings_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedSiteSettings"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedSiteSettings"];
        "multipart/form-data": components["schemas"]["PatchedSiteSettings"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteSettings"];
        };
      };
    };
  };
  admin_media_list: {
    parameters: {
      query?: {
        kind?: "image" | "video";
        /** @description یک شماره صفحه‌ در مجموعه نتایج صفحه‌بندی شده. */
        page?: number;
        /** @description تعداد نتایج برای نمایش در هر صفحه. */
        page_size?: number;
        /** @description Search title, file name and alt texts */
        q?: string;
        status?: "failed" | "pending" | "processing" | "ready";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedMediaAssetList"];
        };
      };
    };
  };
  admin_media_create: {
    parameters: {
      query?: {
        kind?: "image" | "video";
        /** @description Search title, file name and alt texts */
        q?: string;
        status?: "failed" | "pending" | "processing" | "ready";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["MediaUpload"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MediaAsset"];
        };
      };
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MediaAsset"];
        };
      };
    };
  };
  admin_media_retrieve: {
    parameters: {
      query?: {
        kind?: "image" | "video";
        /** @description Search title, file name and alt texts */
        q?: string;
        status?: "failed" | "pending" | "processing" | "ready";
      };
      header?: never;
      path: {
        /** @description یک رشته UUID که این media asset را شناسایی میکند. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MediaAsset"];
        };
      };
    };
  };
  admin_media_destroy: {
    parameters: {
      query?: {
        kind?: "image" | "video";
        /** @description Search title, file name and alt texts */
        q?: string;
        status?: "failed" | "pending" | "processing" | "ready";
      };
      header?: never;
      path: {
        /** @description یک رشته UUID که این media asset را شناسایی میکند. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_media_partial_update: {
    parameters: {
      query?: {
        kind?: "image" | "video";
        /** @description Search title, file name and alt texts */
        q?: string;
        status?: "failed" | "pending" | "processing" | "ready";
      };
      header?: never;
      path: {
        /** @description یک رشته UUID که این media asset را شناسایی میکند. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedMediaAsset"];
        "multipart/form-data": components["schemas"]["PatchedMediaAsset"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MediaAsset"];
        };
      };
    };
  };
  admin_media_original_retrieve: {
    parameters: {
      query?: {
        kind?: "image" | "video";
        /** @description Search title, file name and alt texts */
        q?: string;
        status?: "failed" | "pending" | "processing" | "ready";
      };
      header?: never;
      path: {
        /** @description یک رشته UUID که این media asset را شناسایی میکند. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_media_reprocess_create: {
    parameters: {
      query?: {
        kind?: "image" | "video";
        /** @description Search title, file name and alt texts */
        q?: string;
        status?: "failed" | "pending" | "processing" | "ready";
      };
      header?: never;
      path: {
        /** @description یک رشته UUID که این media asset را شناسایی میکند. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MediaAsset"];
        };
      };
    };
  };
  admin_portfolio_categories_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"][];
        };
      };
    };
  };
  admin_portfolio_categories_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Category"];
        "application/x-www-form-urlencoded": components["schemas"]["Category"];
        "multipart/form-data": components["schemas"]["Category"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"];
        };
      };
    };
  };
  admin_portfolio_categories_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این category را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"];
        };
      };
    };
  };
  admin_portfolio_categories_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این category را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_portfolio_categories_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این category را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedCategory"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedCategory"];
        "multipart/form-data": components["schemas"]["PatchedCategory"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"];
        };
      };
    };
  };
  admin_portfolio_categories_reorder_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderIds"];
        "application/x-www-form-urlencoded": components["schemas"]["ReorderIds"];
        "multipart/form-data": components["schemas"]["ReorderIds"];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_portfolio_projects_list: {
    parameters: {
      query?: {
        category?: number;
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
    };
  };
  admin_portfolio_projects_create: {
    parameters: {
      query?: {
        category?: number;
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Project"];
        "application/x-www-form-urlencoded": components["schemas"]["Project"];
        "multipart/form-data": components["schemas"]["Project"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
    };
  };
  admin_portfolio_projects_retrieve: {
    parameters: {
      query?: {
        category?: number;
        q?: string;
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این project را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
    };
  };
  admin_portfolio_projects_destroy: {
    parameters: {
      query?: {
        category?: number;
        q?: string;
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این project را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_portfolio_projects_partial_update: {
    parameters: {
      query?: {
        category?: number;
        q?: string;
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این project را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedProject"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedProject"];
        "multipart/form-data": components["schemas"]["PatchedProject"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
    };
  };
  admin_portfolio_projects_reorder_create: {
    parameters: {
      query?: {
        category?: number;
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderIds"];
        "application/x-www-form-urlencoded": components["schemas"]["ReorderIds"];
        "multipart/form-data": components["schemas"]["ReorderIds"];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_pricing_groups_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PackageGroup"][];
        };
      };
    };
  };
  admin_pricing_groups_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PackageGroup"];
        "application/x-www-form-urlencoded": components["schemas"]["PackageGroup"];
        "multipart/form-data": components["schemas"]["PackageGroup"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PackageGroup"];
        };
      };
    };
  };
  admin_pricing_groups_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این package group را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PackageGroup"];
        };
      };
    };
  };
  admin_pricing_groups_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این package group را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_pricing_groups_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این package group را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedPackageGroup"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedPackageGroup"];
        "multipart/form-data": components["schemas"]["PatchedPackageGroup"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PackageGroup"];
        };
      };
    };
  };
  admin_pricing_groups_reorder_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderIds"];
        "application/x-www-form-urlencoded": components["schemas"]["ReorderIds"];
        "multipart/form-data": components["schemas"]["ReorderIds"];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_pricing_packages_list: {
    parameters: {
      query?: {
        group?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Package"][];
        };
      };
    };
  };
  admin_pricing_packages_create: {
    parameters: {
      query?: {
        group?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Package"];
        "application/x-www-form-urlencoded": components["schemas"]["Package"];
        "multipart/form-data": components["schemas"]["Package"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Package"];
        };
      };
    };
  };
  admin_pricing_packages_retrieve: {
    parameters: {
      query?: {
        group?: number;
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این package را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Package"];
        };
      };
    };
  };
  admin_pricing_packages_destroy: {
    parameters: {
      query?: {
        group?: number;
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این package را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_pricing_packages_partial_update: {
    parameters: {
      query?: {
        group?: number;
      };
      header?: never;
      path: {
        /** @description یک مقداد عدد یکتا که این package را شناسایی میکند. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedPackage"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedPackage"];
        "multipart/form-data": components["schemas"]["PatchedPackage"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Package"];
        };
      };
    };
  };
  admin_pricing_packages_reorder_create: {
    parameters: {
      query?: {
        group?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderIds"];
        "application/x-www-form-urlencoded": components["schemas"]["ReorderIds"];
        "multipart/form-data": components["schemas"]["ReorderIds"];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_settings_watermark_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WatermarkSetting"];
        };
      };
    };
  };
  admin_settings_watermark_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["WatermarkSetting"];
        "application/x-www-form-urlencoded": components["schemas"]["WatermarkSetting"];
        "multipart/form-data": components["schemas"]["WatermarkSetting"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WatermarkSetting"];
        };
      };
    };
  };
  auth_csrf_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_login_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Credentials"];
        "application/x-www-form-urlencoded": components["schemas"]["Credentials"];
        "multipart/form-data": components["schemas"]["Credentials"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["State"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  auth_logout_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["State"];
        };
      };
    };
  };
  auth_password_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChange"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
        "multipart/form-data": components["schemas"]["PasswordChange"];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  auth_recovery_codes_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Password"];
        "application/x-www-form-urlencoded": components["schemas"]["Password"];
        "multipart/form-data": components["schemas"]["Password"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecoveryCodes"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  auth_totp_confirm_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Code"];
        "application/x-www-form-urlencoded": components["schemas"]["Code"];
        "multipart/form-data": components["schemas"]["Code"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecoveryCodes"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  auth_totp_setup_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TotpSetup"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  auth_verify_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Code"];
        "application/x-www-form-urlencoded": components["schemas"]["Code"];
        "multipart/form-data": components["schemas"]["Code"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["State"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  public_blog_articles_list: {
    parameters: {
      query: {
        /** @description Category slug */
        category?: string;
        lang: "en" | "fa";
        page?: number;
        /** @description Tag slug */
        tag?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicBlogArticlePage"];
        };
      };
    };
  };
  public_blog_article_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lang: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicBlogArticleDetail"];
        };
      };
      301: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArticleMoved"];
        };
      };
    };
  };
  public_blog_preview_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicBlogArticleDetail"];
        };
      };
    };
  };
  public_blog_taxonomy_retrieve: {
    parameters: {
      query: {
        lang: "en" | "fa";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicBlogTaxonomy"];
        };
      };
    };
  };
  public_packages_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicPackages"];
        };
      };
    };
  };
  public_portfolio_list: {
    parameters: {
      query?: {
        /** @description Category slug */
        category?: string;
        featured?: boolean;
        style?: "high_key" | "low_key" | "natural";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicPortfolio"];
        };
      };
    };
  };
  public_project_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicProjectDetail"];
        };
      };
    };
  };
  public_site_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicSite"];
        };
      };
    };
  };
  public_sitemap_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicSitemap"];
        };
      };
    };
  };
}
