# Generated by Django 5.2.17 on 2026-10-03 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_fa", models.CharField(max_length=160)),
                ("title_en", models.CharField(blank=True, max_length=160)),
                ("summary_fa", models.TextField(blank=True)),
                ("summary_en", models.TextField(blank=True)),
                (
                    "price_mode",
                    models.CharField(
                        choices=[
                            ("from", "از … شروع می\u200cشود"),
                            ("fixed", "قیمت ثابت"),
                            ("inquiry", "استعلام"),
                        ],
                        default="inquiry",
                        max_length=8,
                    ),
                ),
                (
                    "price_amount",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Toman", null=True
                    ),
                ),
                (
                    "price_unit_fa",
                    models.CharField(
                        blank=True, help_text="e.g. «به ازای هر محصول»", max_length=60
                    ),
                ),
                ("price_unit_en", models.CharField(blank=True, max_length=60)),
                (
                    "badge_fa",
                    models.CharField(
                        blank=True, help_text="e.g. «محبوب»", max_length=40
                    ),
                ),
                ("badge_en", models.CharField(blank=True, max_length=40)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="PackageGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_fa", models.CharField(max_length=120)),
                ("title_en", models.CharField(blank=True, max_length=120)),
                ("description_fa", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="PackageFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_fa", models.CharField(max_length=200)),
                ("text_en", models.CharField(blank=True, max_length=200)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="pricing.package",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="package",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="pricing.packagegroup",
            ),
        ),
    ]
