# Generated by Django 5.2.17 on 2026-10-03 17:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "range_percent",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="The estimate is shown as total ± this percent",
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                (
                    "rounding_step",
                    models.PositiveIntegerField(
                        default=10000,
                        help_text="Both ends of the range are rounded to this many toman",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        default=200,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "quote settings",
            },
        ),
        migrations.CreateModel(
            name="QuoteRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier used by the public form",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "قیمت پایه\u200cی خدمت (هر محصول)"),
                            ("tier", "پله\u200cی تعداد (ضریب از تعداد مشخص به بعد)"),
                            ("addon_fixed", "افزونه\u200cی ثابت"),
                            ("addon_per_item", "افزونه به\u200cازای هر محصول"),
                            ("multiplier", "ضریب (مثل فوریت)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label_fa", models.CharField(max_length=120)),
                ("label_en", models.CharField(blank=True, max_length=120)),
                (
                    "amount",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Toman", null=True
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("20")),
                        ],
                    ),
                ),
                ("min_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "kind__in",
                                    ["service", "addon_fixed", "addon_per_item"],
                                ),
                                _negated=True,
                            ),
                            ("amount__isnull", False),
                            _connector="OR",
                        ),
                        name="quoterule_amount_for_priced_kinds",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "tier"), _negated=True),
                            models.Q(
                                ("factor__isnull", False),
                                ("min_quantity__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="quoterule_tier_needs_factor_and_quantity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "multiplier"), _negated=True),
                            ("factor__isnull", False),
                            _connector="OR",
                        ),
                        name="quoterule_multiplier_needs_factor",
                    ),
                ],
            },
        ),
    ]
