# Generated by Django 5.2.17 on 2026-10-03 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=80, unique=True),
                ),
                ("title_fa", models.CharField(max_length=120)),
                ("title_en", models.CharField(blank=True, max_length=120)),
                ("description_fa", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["title_fa", "id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=80, unique=True),
                ),
                ("title_fa", models.CharField(max_length=80)),
                ("title_en", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["title_fa", "id"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fa", "فارسی"), ("en", "English")], max_length=2
                    ),
                ),
                (
                    "translation_group",
                    models.UUIDField(db_index=True, default=uuid.uuid4),
                ),
                ("slug", models.SlugField(allow_unicode=True, max_length=120)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("body", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "پیش\u200cنویس"), ("published", "منتشرشده")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("reading_minutes", models.PositiveSmallIntegerField(default=1)),
                ("seo_title", models.CharField(blank=True, max_length=120)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "related_projects",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="portfolio.project"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="blog.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="blog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleSlugRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fa", "فارسی"), ("en", "English")], max_length=2
                    ),
                ),
                ("old_slug", models.SlugField(allow_unicode=True, max_length=120)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redirects",
                        to="blog.article",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language", "old_slug"),
                        name="unique_redirect_per_language",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["language", "status", "published_at"],
                name="blog_articl_languag_574ab7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                fields=("language", "slug"), name="unique_article_slug_per_language"
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                fields=("translation_group", "language"),
                name="one_article_per_language_in_group",
            ),
        ),
    ]
