/** Every message the proforma page shows; read on the server and passed down, so the client carries no message files. */
export const PROFORMA_LABEL_KEYS = [
  "title",
  "number",
  "issued",
  "validUntil",
  "customer",
  "description",
  "quantity",
  "unitPrice",
  "amount",
  "subtotal",
  "discount",
  "tax",
  "total",
  "toman",
  "terms",
  "downloadPdf",
  "approve",
  "reject",
  "reasonLabel",
  "confirmReject",
  "cancel",
  "working",
  "approvedTitle",
  "approvedBody",
  "rejectedTitle",
  "rejectedBody",
  "expiredTitle",
  "expiredBody",
  "supersededTitle",
  "supersededBody",
  "cancelledTitle",
  "cancelledBody",
  "errorGeneric",
  "errorRate",
  "decision",
  "decisionHint",
  "reasonShown",
] as const;

export type ProformaLabels = Record<(typeof PROFORMA_LABEL_KEYS)[number], string>;
