# Generated by Django 5.2.17 on 2026-10-03 18:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProformaCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProformaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer_name_fa", models.CharField(blank=True, max_length=120)),
                ("issuer_name_en", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address_fa", models.CharField(blank=True, max_length=300)),
                ("address_en", models.CharField(blank=True, max_length=300)),
                ("terms_fa", models.TextField(blank=True)),
                ("terms_en", models.TextField(blank=True)),
                ("footer_fa", models.CharField(blank=True, max_length=300)),
                ("footer_en", models.CharField(blank=True, max_length=300)),
                (
                    "default_validity_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "default_tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "proforma settings",
            },
        ),
        migrations.CreateModel(
            name="Proforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("link_version", models.PositiveIntegerField(default=1)),
                (
                    "number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("sent", "ارسال\u200cشده"),
                            ("viewed", "دیده\u200cشده"),
                            ("approved", "تأییدشده"),
                            ("rejected", "ردشده"),
                            ("superseded", "جایگزین\u200cشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fa", "فارسی"), ("en", "English")],
                        default="fa",
                        max_length=2,
                    ),
                ),
                ("customer_name", models.CharField(max_length=120)),
                ("customer_company", models.CharField(blank=True, max_length=120)),
                ("customer_contact", models.CharField(blank=True, max_length=200)),
                (
                    "discount_amount",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Toman; use this or the percent, not both"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("subtotal", models.PositiveBigIntegerField(default=0)),
                ("discount", models.PositiveBigIntegerField(default=0)),
                ("tax", models.PositiveBigIntegerField(default=0)),
                ("total", models.PositiveBigIntegerField(default=0)),
                ("terms", models.TextField(blank=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "issuer",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Who issued it, frozen when it was issued",
                    ),
                ),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response_ip_hash", models.CharField(blank=True, max_length=64)),
                ("response_user_agent", models.CharField(blank=True, max_length=200)),
                ("rejection_reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proformas",
                        to="inquiries.inquiry",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_by",
                        to="proformas.proforma",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProformaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_price", models.PositiveBigIntegerField(help_text="Toman")),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="proformas.proforma",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(
                fields=["status", "-created_at"], name="proformas_p_status_9f47d9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="proforma",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_amount__gt", 0),
                    ("discount_percent__gt", 0),
                    _negated=True,
                ),
                name="proforma_one_kind_of_discount",
            ),
        ),
    ]
