# Generated by Django 5.2.17 on 2026-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proformas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proforma",
            name="anonymized_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Customer personal details were removed",
                null=True,
            ),
        ),
    ]
