# Generated by Django 5.2.17 on 2026-10-04 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RetentionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Off: nothing is ever anonymised or deleted",
                    ),
                ),
                (
                    "inquiry_months",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="Enquiries, then anonymised",
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "booking_months",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="Months after the session, then anonymised",
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "gallery_days",
                    models.PositiveSmallIntegerField(
                        default=90,
                        help_text="Days after a gallery expired or was archived, then deleted with all its files",
                        validators=[
                            django.core.validators.MinValueValidator(7),
                            django.core.validators.MaxValueValidator(730),
                        ],
                    ),
                ),
                (
                    "proforma_months",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Months after issue; only the customer's personal details are anonymised",
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(240),
                        ],
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "retention settings",
            },
        ),
    ]
