# Generated by Django 5.2.17 on 2026-10-03 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("text_fa", models.TextField(blank=True)),
                ("text_en", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name_fa",
                    models.CharField(default="سودا رحیم\u200cپور", max_length=120),
                ),
                (
                    "brand_name_en",
                    models.CharField(default="Sevda Rahimpour", max_length=120),
                ),
                (
                    "tagline_fa",
                    models.CharField(
                        blank=True, default="عکاسی غذا و محصول", max_length=200
                    ),
                ),
                (
                    "tagline_en",
                    models.CharField(
                        blank=True, default="Food & product photography", max_length=200
                    ),
                ),
                (
                    "description_fa",
                    models.TextField(blank=True, help_text="Default meta description"),
                ),
                ("description_en", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("whatsapp", models.CharField(blank=True, max_length=120)),
                ("telegram", models.CharField(blank=True, max_length=120)),
                (
                    "instagram",
                    models.CharField(blank=True, default="3evda.r", max_length=120),
                ),
                (
                    "address_fa",
                    models.CharField(blank=True, default="ارومیه", max_length=300),
                ),
                (
                    "address_en",
                    models.CharField(blank=True, default="Urmia, Iran", max_length=300),
                ),
                ("map_url", models.URLField(blank=True)),
                ("footer_text_fa", models.TextField(blank=True)),
                ("footer_text_en", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.CharField(
                        choices=[
                            ("hero_slide", "اسلاید هیرو"),
                            ("service", "خدمت"),
                            ("process_step", "مرحله\u200cی همکاری"),
                            ("client", "مشتری"),
                            ("testimonial", "نظر مشتری"),
                            ("behind_scenes", "پشت صحنه"),
                            ("faq", "پرسش پرتکرار"),
                            ("nav_link", "پیوند منو"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("title_fa", models.CharField(blank=True, max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("subtitle_fa", models.CharField(blank=True, max_length=300)),
                ("subtitle_en", models.CharField(blank=True, max_length=300)),
                ("body_fa", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
                ("link_url", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["collection", "position", "id"],
                "indexes": [
                    models.Index(
                        fields=["collection", "is_published", "position"],
                        name="cms_content_collect_d0a0cc_idx",
                    )
                ],
            },
        ),
    ]
