# Generated by Django 5.2.17 on 2026-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="font_fa_body",
            field=models.CharField(
                choices=[
                    ("vazirmatn", "وزیرمتن (پیش\u200cفرض)"),
                    ("noto-sans", "نوتو سنس عربی"),
                    ("ibm-plex", "آی\u200cبی\u200cام پلکس عربی"),
                    ("cairo", "قاهره"),
                    ("noto-naskh", "نوتو نسخ"),
                    ("amiri", "امیری"),
                    ("harmattan", "هارماتان"),
                    ("almarai", "المرعی"),
                ],
                default="vazirmatn",
                help_text="Persian body text typeface",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="font_fa_heading",
            field=models.CharField(
                choices=[
                    ("vazirmatn", "وزیرمتن (پیش\u200cفرض)"),
                    ("noto-sans", "نوتو سنس عربی"),
                    ("ibm-plex", "آی\u200cبی\u200cام پلکس عربی"),
                    ("cairo", "قاهره"),
                    ("noto-naskh", "نوتو نسخ"),
                    ("amiri", "امیری"),
                    ("harmattan", "هارماتان"),
                    ("almarai", "المرعی"),
                    ("lalezar", "لاله\u200cزار (فقط تیتر)"),
                ],
                default="vazirmatn",
                help_text="Persian headings typeface",
                max_length=20,
            ),
        ),
    ]
