# Generated by Django 5.2.17 on 2026-10-03 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title_fa", models.CharField(max_length=120)),
                ("title_en", models.CharField(blank=True, max_length=120)),
                ("description_fa", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low_key", "Low-key"),
                            ("high_key", "High-key"),
                            ("natural", "نور طبیعی"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title_fa", models.CharField(max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("summary_fa", models.TextField(blank=True)),
                ("summary_en", models.TextField(blank=True)),
                ("body_fa", models.TextField(blank=True, help_text="Case study")),
                ("body_en", models.TextField(blank=True)),
                ("client_fa", models.CharField(blank=True, max_length=120)),
                ("client_en", models.CharField(blank=True, max_length=120)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="portfolio.category",
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption_fa", models.CharField(blank=True, max_length=300)),
                ("caption_en", models.CharField(blank=True, max_length=300)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_published", "position"],
                name="portfolio_p_is_publ_9a683b_idx",
            ),
        ),
    ]
