# Generated by Django 5.2.17 on 2026-10-03 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("whatsapp", models.CharField(blank=True, max_length=120)),
                ("telegram", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("language", models.CharField(default="fa", max_length=2)),
                ("service_key", models.CharField(blank=True, max_length=40)),
                ("service_label", models.CharField(blank=True, max_length=120)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("estimate_low", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "estimate_high",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("reviewing", "در بررسی"),
                            ("proforma_sent", "پیش\u200cفاکتور ارسال شد"),
                            ("converted", "تبدیل شد (رزرو یا پروژه)"),
                            ("closed", "بسته"),
                        ],
                        default="new",
                        max_length=14,
                    ),
                ),
                ("internal_note", models.TextField(blank=True)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                (
                    "seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="First time the owner opened it",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "inquiries",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="inquiries_i_status_152cc6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InquiryAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("original_name", models.CharField(max_length=200)),
                ("mime", models.CharField(max_length=60)),
                ("size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="inquiries.inquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="InquiryStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("reviewing", "در بررسی"),
                            ("proforma_sent", "پیش\u200cفاکتور ارسال شد"),
                            ("converted", "تبدیل شد (رزرو یا پروژه)"),
                            ("closed", "بسته"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("reviewing", "در بررسی"),
                            ("proforma_sent", "پیش\u200cفاکتور ارسال شد"),
                            ("converted", "تبدیل شد (رزرو یا پروژه)"),
                            ("closed", "بسته"),
                        ],
                        max_length=14,
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="inquiries.inquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["at", "id"],
            },
        ),
    ]
