# Generated by Django 5.2.17 on 2026-10-02 20:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatermarkSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("text", models.CharField(default="© 3evda.com", max_length=80)),
                (
                    "opacity",
                    models.FloatField(
                        default=0.35,
                        validators=[
                            django.core.validators.MinValueValidator(0.05),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("bottom_right", "پایین راست"),
                            ("bottom_left", "پایین چپ"),
                            ("top_right", "بالا راست"),
                            ("top_left", "بالا چپ"),
                            ("center", "وسط"),
                        ],
                        default="bottom_right",
                        max_length=16,
                    ),
                ),
                (
                    "size_ratio",
                    models.FloatField(
                        default=0.035,
                        help_text="text height / width",
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(0.2),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "تصویر"), ("video", "ویدیو")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در صف"),
                            ("processing", "در حال پردازش"),
                            ("ready", "آماده"),
                            ("failed", "ناموفق"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("original_key", models.CharField(max_length=255, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("mime", models.CharField(max_length=50)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "alt_fa",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="متن جایگزین (فارسی)"
                    ),
                ),
                (
                    "alt_en",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="متن جایگزین (انگلیسی)"
                    ),
                ),
                ("lqip", models.TextField(blank=True)),
                ("watermarked", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                ("field", models.CharField(max_length=64)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="references",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "content_type", "object_id", "field"),
                        name="unique_reference",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MediaVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("format", models.CharField(max_length=8)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("size_bytes", models.PositiveBigIntegerField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "format"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "name", "format"), name="unique_variant"
                    )
                ],
            },
        ),
    ]
