# Generated by Django 5.2.17 on 2026-10-03 19:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inquiries", "0001_initial"),
        ("pricing", "0002_quote_rules"),
        ("proformas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_per_day",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Active bookings per day",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "min_notice_hours",
                    models.PositiveSmallIntegerField(
                        default=24,
                        validators=[django.core.validators.MaxValueValidator(720)],
                    ),
                ),
                (
                    "horizon_days",
                    models.PositiveSmallIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "booking settings",
            },
        ),
        migrations.CreateModel(
            name="SessionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=40, unique=True)),
                ("title_fa", models.CharField(max_length=120)),
                ("title_en", models.CharField(blank=True, max_length=120)),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(720),
                        ]
                    ),
                ),
                (
                    "buffer_minutes",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(240)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClosedPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["start_date", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="closed_end_not_before_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(6)]
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
            ],
            options={
                "ordering": ["weekday", "start"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end__gt", models.F("start"))),
                        name="workinghours_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تأیید"),
                            ("confirmed", "تأییدشده"),
                            ("completed", "انجام\u200cشده"),
                            ("cancelled", "لغو"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fa", "فارسی"), ("en", "English")],
                        default="fa",
                        max_length=2,
                    ),
                ),
                (
                    "session_label",
                    models.CharField(
                        help_text="Title as the customer saw it", max_length=120
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("blocked_until", models.DateTimeField()),
                ("name", models.CharField(max_length=120)),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("whatsapp", models.CharField(blank=True, max_length=120)),
                ("telegram", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True, max_length=2000)),
                ("package_label", models.CharField(blank=True, max_length=120)),
                ("internal_note", models.TextField(blank=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[("customer", "مشتری"), ("admin", "ادمین")],
                        max_length=10,
                    ),
                ),
                ("cancel_reason", models.CharField(blank=True, max_length=300)),
                ("created_by_admin", models.BooleanField(default=False)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="inquiries.inquiry",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="pricing.package",
                    ),
                ),
                (
                    "proforma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="proformas.proforma",
                    ),
                ),
                (
                    "session_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="booking.sessiontype",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "start_at"],
                        name="booking_boo_status_bcac9d_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="booking_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("blocked_until__gte", models.F("end_at"))),
                        name="booking_blocked_after_end",
                    ),
                ],
            },
        ),
    ]
