# Generated by Django 5.2.17 on 2026-10-04 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("inquiries", "0001_initial"),
        ("proformas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("link_version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=160)),
                ("client_name", models.CharField(blank=True, max_length=120)),
                (
                    "language",
                    models.CharField(
                        choices=[("fa", "فارسی"), ("en", "English")],
                        default="fa",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشرشده"),
                            ("submitted", "نهایی\u200cشده"),
                            ("archived", "بایگانی"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("password_hash", models.CharField(blank=True, max_length=256)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "selection_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Empty: no limit", null=True
                    ),
                ),
                (
                    "download_level",
                    models.CharField(
                        choices=[
                            ("none", "فقط دیدن"),
                            ("selected", "انتخاب\u200cها (اندازه\u200cی نمایش)"),
                            ("all_web", "همه (اندازه\u200cی نمایش)"),
                            ("original", "اصل فایل\u200cها"),
                        ],
                        default="selected",
                        max_length=10,
                    ),
                ),
                (
                    "watermark",
                    models.BooleanField(
                        default=True, help_text="Previews carry the watermark"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Private; never shown to the client"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galleries",
                        to="booking.booking",
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galleries",
                        to="inquiries.inquiry",
                    ),
                ),
                (
                    "proforma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galleries",
                        to="proformas.proforma",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "galleries",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در صف"),
                            ("ready", "آماده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("original_key", models.CharField(max_length=255, unique=True)),
                ("thumb_key", models.CharField(blank=True, max_length=255)),
                ("preview_key", models.CharField(blank=True, max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                ("mime", models.CharField(max_length=50)),
                ("size_bytes", models.PositiveBigIntegerField()),
                (
                    "stored_bytes",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Thumbnail and preview together"
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="galleries.gallery",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="gallery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("selection_limit__isnull", True),
                    ("selection_limit__gt", 0),
                    _connector="OR",
                ),
                name="gallery_limit_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="galleryphoto",
            constraint=models.UniqueConstraint(
                fields=("gallery", "sha256"), name="gallery_photo_unique_content"
            ),
        ),
    ]
