# Generated by Django 5.2.17 on 2026-10-04 06:37

import apps.galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, default=apps.galleries.models.default_expiry, null=True
            ),
        ),
    ]
