# Generated by Django 5.2.17 on 2026-10-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0002_expiry_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="Selection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected", models.BooleanField(default=False)),
                ("comment", models.CharField(blank=True, max_length=500)),
                ("retouch", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selection",
                        to="galleries.galleryphoto",
                    ),
                ),
            ],
        ),
    ]
