# Generated by Django 5.2.17 on 2026-10-04 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0003_selection"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "عکس"), ("zip", "ZIP"), ("final", "نهایی")],
                        max_length=10,
                    ),
                ),
                ("files", models.PositiveIntegerField(default=1)),
                ("originals", models.BooleanField(default=False)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="galleries.gallery",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FinalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("filename", models.CharField(max_length=255)),
                ("mime", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finals",
                        to="galleries.gallery",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ZipJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "در صف"),
                            ("running", "در حال ساخت"),
                            ("ready", "آماده"),
                            ("failed", "ناموفق"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "originals",
                    models.BooleanField(
                        default=False,
                        help_text="Original files instead of display size",
                    ),
                ),
                ("only_selected", models.BooleanField(default=True)),
                ("total", models.PositiveIntegerField(default=0)),
                ("done", models.PositiveIntegerField(default=0)),
                ("key", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zips",
                        to="galleries.gallery",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["queued", "running"])),
                        fields=("gallery",),
                        name="one_active_zip_per_gallery",
                    )
                ],
            },
        ),
    ]
