# Generated by Django 5.2.17 on 2026-10-05 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SampleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("empty", "بارگذاری نشده"),
                            ("loading", "در حال بارگذاری"),
                            ("loaded", "بارگذاری\u200cشده"),
                            ("unloading", "در حال پاک\u200cسازی"),
                            ("failed", "ناموفق"),
                        ],
                        default="empty",
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=500)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Lease: only the task holding the current id may write",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "sample state",
            },
        ),
        migrations.CreateModel(
            name="SampleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("object", "object"), ("field", "field")], max_length=6
                    ),
                ),
                ("model_label", models.CharField(max_length=60)),
                ("object_id", models.CharField(max_length=64)),
                ("field", models.CharField(blank=True, max_length=64)),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Field records: what the loader wrote",
                        max_length=300,
                    ),
                ),
                ("group", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["kind", "model_label"],
                        name="sampleconte_kind_ee4944_idx",
                    )
                ],
            },
        ),
    ]
